### ISSUE TITLE
node.js:201 throw e; // process.nextTick error, or 'error' event on first tick

### ISSUE THREAD

**Issue by mars1985** [tadast/webattle.js#2]
Hello I am very new to node.js and I am trying to run this webattle.js local in ubuntu.

Do you know what I am doing wrong here?

cloudev@ubuntu:~$ cd webattle
cloudev@ubuntu:~/webattle$ npm install

cloudev@ubuntu:~/webattle$ node server.js
3 Dec 06:53:14 - socket.io ready - accepting connections
Server is running on http://localhost:4000

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: listen EACCESS
    at errnoException (net.js:614:11)
    at Array.1 (net.js:689:28)
    at EventEmitter._tickCallback (node.js:192:40)

**Comment by mars1985** [comment]
Nevermind!!!! I am very new and I was not running as root - "sudo node server,js"

**Comment by tadast** [comment]
You shouldn't require root access to run node.js server unless you want it to run on port 80 or so. If you don't, probably there are some issues with your node.js installation permissions.

**Comment by mars1985** [comment]
Thank you for your help and quick response. I have decided to give it a try on cloud9 IDE so I could have a live experience. 

http://c9.io/mars1985/webattle_js 

Demo Example: http://webattle_js.mars1985.c9.io/ 
It seems to be running but not displaying?

3 Dec 19:07:49 - socket.io ready - accepting connections
Server is running on http://0.0.0.0:34385

The only thing that I changed was the config file to run using cloud9.

this.port = process.env.PORT;
this.ip = "0.0.0.0";

Any thoughts on why its not rendering?

**Comment by tadast** [comment]
In short, you have to set the IP of your server. 

Longer explanation: if you set the ip to 0.0.0.0 it will work locally, but not in the server. This setting is being used by the client side js code, therefore when a user loads the page, client side js will try to connect to WebSockets server on 0.0.0.0, which should actually point to the server where the game is hosted. You can actually set this.ip to domain name as well, it worked for me at least.

**Comment by mars1985** [comment]
I think I understand from a normal server setup but for Cloud9 they ask you to use 0.0.0.0:

"Tip: you can access long running processes, like a server, at 'http://webattle_js.mars1985.c9.io'.
Important: in your scripts, use 'process.env.PORT' as port and '0.0.0.0' as host."

So I guess this may not be possible to run on cloud9.

Thank you!
